# Generated by Django 4.1.2 on 2022-10-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containers',
            name='id',
        ),
        migrations.AddField(
            model_name='containers',
            name='ID',
            field=models.CharField(default=1111, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
