# Generated by Django 4.1.3 on 2022-11-12 22:47

from django.db import migrations, models
import rest_app.models_validation


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0005_alter_containers_number_containerorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='containers',
            name='arrival_city',
            field=models.CharField(max_length=50, validators=[rest_app.models_validation.ContainerValidation.validate_city]),
        ),
        migrations.AlterField(
            model_name='containers',
            name='departure_city',
            field=models.CharField(max_length=50, validators=[rest_app.models_validation.ContainerValidation.validate_city]),
        ),
    ]
