# Generated by Django 4.1.2 on 2022-10-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_remove_containers_id_containers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='containers',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='containers',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
